from diffusers import StableDiffusionPipeline
import torch
import argparse
import os

parser = argparse.ArgumentParser(description="Simple example of a training script.")
parser.add_argument(
    "--model_path",
    type=str,
    default=None,
)
parser.add_argument(
    "--save_path",
    type=str,
    default=None,
)
args = parser.parse_args()

model_path = args.model_path
pipe = StableDiffusionPipeline.from_pretrained("/path/stable-diffusion-1-5", torch_dtype=torch.float16)
pipe.safety_checker = None
pipe.requires_safety_checker = False
pipe.load_lora_weights(model_path)
pipe.to("cuda")

if not os.path.exists(args.save_path):
    os.makedirs(args.save_path)


prompt_list = ["a painting of cityscape,Northern_Renaissance by albrecht-durer",
"a painting of genre_painting,Northern_Renaissance by albrecht-durer",
"a painting of landscape,Northern_Renaissance by albrecht-durer",
"a painting of nude_painting,Northern_Renaissance by albrecht-durer",
"a painting of cityscape,Northern_Renaissance by albrecht-durer",
"a painting of genre_painting,Northern_Renaissance by albrecht-durer",
"a painting of landscape,Northern_Renaissance by albrecht-durer",
"a painting of nude_painting,Northern_Renaissance by albrecht-durer",
"a painting of cityscape,Northern_Renaissance by albrecht-durer",
"a painting of genre_painting,Northern_Renaissance by albrecht-durer",
"a painting of cityscape,Impressionism by childe-hassam",
"a painting of genre_painting,Impressionism by childe-hassam",
"a painting of landscape,Impressionism by childe-hassam",
"a painting of nude_painting,Impressionism by childe-hassam",
"a painting of cityscape,Impressionism by childe-hassam",
"a painting of genre_painting,Impressionism by childe-hassam",
"a painting of landscape,Impressionism by childe-hassam",
"a painting of nude_painting,Impressionism by childe-hassam",
"a painting of cityscape,Impressionism by childe-hassam",
"a painting of genre_painting,Impressionism by childe-hassam",
"a painting of cityscape,Impressionism by claude-monet",
"a painting of cityscape,Realism by claude-monet",
"a painting of genre_painting,Impressionism by claude-monet",
"a painting of portrait,Impressionism by claude-monet",
"a painting of cityscape,Impressionism by claude-monet",
"a painting of cityscape,Realism by claude-monet",
"a painting of genre_painting,Impressionism by claude-monet",
"a painting of portrait,Impressionism by claude-monet",
"a painting of cityscape,Impressionism by claude-monet",
"a painting of cityscape,Realism by claude-monet",
"a painting of genre_painting,Impressionism by edgar-degas",
"a painting of landscape,Impressionism by edgar-degas",
"a painting of nude_painting,Impressionism by edgar-degas",
"a painting of portrait,Impressionism by edgar-degas",
"a painting of genre_painting,Impressionism by edgar-degas",
"a painting of landscape,Impressionism by edgar-degas",
"a painting of nude_painting,Impressionism by edgar-degas",
"a painting of portrait,Impressionism by edgar-degas",
"a painting of genre_painting,Impressionism by edgar-degas",
"a painting of landscape,Impressionism by edgar-degas",
"a painting of cityscape,Impressionism by eugene-boudin",
"a painting of cityscape,Realism by eugene-boudin",
"a painting of genre_painting,Impressionism by eugene-boudin",
"a painting of genre_painting,Realism by eugene-boudin",
"a painting of cityscape,Impressionism by eugene-boudin",
"a painting of cityscape,Realism by eugene-boudin",
"a painting of genre_painting,Impressionism by eugene-boudin",
"a painting of genre_painting,Realism by eugene-boudin",
"a painting of cityscape,Impressionism by eugene-boudin",
"a painting of cityscape,Realism by eugene-boudin",
"a painting of cityscape,Realism by ilya-repin",
"a painting of genre_painting,Realism by ilya-repin",
"a painting of landscape,Realism by ilya-repin",
"a painting of portrait,Impressionism by ilya-repin",
"a painting of cityscape,Realism by ilya-repin",
"a painting of genre_painting,Realism by ilya-repin",
"a painting of landscape,Realism by ilya-repin",
"a painting of portrait,Impressionism by ilya-repin",
"a painting of cityscape,Realism by ilya-repin",
"a painting of genre_painting,Realism by ilya-repin",
"a painting of cityscape,Impressionism by john-singer-sargent",
"a painting of cityscape,Realism by john-singer-sargent",
"a painting of genre_painting,Impressionism by john-singer-sargent",
"a painting of genre_painting,Realism by john-singer-sargent",
"a painting of cityscape,Impressionism by john-singer-sargent",
"a painting of cityscape,Realism by john-singer-sargent",
"a painting of genre_painting,Impressionism by john-singer-sargent",
"a painting of genre_painting,Realism by john-singer-sargent",
"a painting of cityscape,Impressionism by john-singer-sargent",
"a painting of cityscape,Realism by john-singer-sargent",
"a painting of cityscape,Impressionism by pierre-auguste-renoir",
"a painting of genre_painting,Impressionism by pierre-auguste-renoir",
"a painting of landscape,Impressionism by pierre-auguste-renoir",
"a painting of landscape,Realism by pierre-auguste-renoir",
"a painting of cityscape,Impressionism by pierre-auguste-renoir",
"a painting of genre_painting,Impressionism by pierre-auguste-renoir",
"a painting of landscape,Impressionism by pierre-auguste-renoir",
"a painting of landscape,Realism by pierre-auguste-renoir",
"a painting of cityscape,Impressionism by pierre-auguste-renoir",
"a painting of genre_painting,Impressionism by pierre-auguste-renoir",
"a painting of cityscape,Baroque by rembrandt",
"a painting of genre_painting,Baroque by rembrandt",
"a painting of landscape,Baroque by rembrandt",
"a painting of religious_painting,Baroque by rembrandt",
"a painting of cityscape,Baroque by rembrandt",
"a painting of genre_painting,Baroque by rembrandt",
"a painting of landscape,Baroque by rembrandt",
"a painting of religious_painting,Baroque by rembrandt",
"a painting of cityscape,Baroque by rembrandt",
"a painting of genre_painting,Baroque by rembrandt",
"a painting of cityscape,Post_Impressionism by vincent-van-gogh",
"a painting of cityscape,Realism by vincent-van-gogh",
"a painting of genre_painting,Post_Impressionism by vincent-van-gogh",
"a painting of still_life,Realism by vincent-van-gogh",
"a painting of cityscape,Post_Impressionism by vincent-van-gogh",
"a painting of cityscape,Realism by vincent-van-gogh",
"a painting of genre_painting,Post_Impressionism by vincent-van-gogh",
"a painting of still_life,Realism by vincent-van-gogh",
"a painting of cityscape,Post_Impressionism by vincent-van-gogh",
"a painting of cityscape,Realism by vincent-van-gogh",
]

'''prompt_list = [
    "a painting in the style of albrecht-durer",
    "a painting in the style of albrecht-durer",
    "a painting in the style of albrecht-durer",
    "a painting in the style of albrecht-durer",
    "a painting in the style of albrecht-durer",
    "a painting in the style of albrecht-durer",
    "a painting in the style of albrecht-durer",
    "a painting in the style of albrecht-durer",
    "a painting in the style of albrecht-durer",
    "a painting in the style of albrecht-durer",
    "a painting in the style of childe-hassam",
    "a painting in the style of childe-hassam",
    "a painting in the style of childe-hassam",
    "a painting in the style of childe-hassam",
    "a painting in the style of childe-hassam",
    "a painting in the style of childe-hassam",
    "a painting in the style of childe-hassam",
    "a painting in the style of childe-hassam",
    "a painting in the style of childe-hassam",
    "a painting in the style of childe-hassam",
    "a painting in the style of claude-monet",
    "a painting in the style of claude-monet",
    "a painting in the style of claude-monet",
    "a painting in the style of claude-monet",
    "a painting in the style of claude-monet",
    "a painting in the style of claude-monet",
    "a painting in the style of claude-monet",
    "a painting in the style of claude-monet",
    "a painting in the style of claude-monet",
    "a painting in the style of claude-monet",
    "a painting in the style of edgar-degas",
    "a painting in the style of edgar-degas",
    "a painting in the style of edgar-degas",
    "a painting in the style of edgar-degas",
    "a painting in the style of edgar-degas",
    "a painting in the style of edgar-degas",
    "a painting in the style of edgar-degas",
    "a painting in the style of edgar-degas",
    "a painting in the style of edgar-degas",
    "a painting in the style of edgar-degas",
    "a painting in the style of eugene-boudin",
    "a painting in the style of eugene-boudin",
    "a painting in the style of eugene-boudin",
    "a painting in the style of eugene-boudin",
    "a painting in the style of eugene-boudin",
    "a painting in the style of eugene-boudin",
    "a painting in the style of eugene-boudin",
    "a painting in the style of eugene-boudin",
    "a painting in the style of eugene-boudin",
    "a painting in the style of eugene-boudin",
    "a painting in the style of ilya-repin",
    "a painting in the style of ilya-repin",
    "a painting in the style of ilya-repin",
    "a painting in the style of ilya-repin",
    "a painting in the style of ilya-repin",
    "a painting in the style of ilya-repin",
    "a painting in the style of ilya-repin",
    "a painting in the style of ilya-repin",
    "a painting in the style of ilya-repin",
    "a painting in the style of ilya-repin",
    "a painting in the style of john-singer-sargent",
    "a painting in the style of john-singer-sargent",
    "a painting in the style of john-singer-sargent",
    "a painting in the style of john-singer-sargent",
    "a painting in the style of john-singer-sargent",
    "a painting in the style of john-singer-sargent",
    "a painting in the style of john-singer-sargent",
    "a painting in the style of john-singer-sargent",
    "a painting in the style of john-singer-sargent",
    "a painting in the style of john-singer-sargent",
    "a painting in the style of pierre-auguste-renoir",
    "a painting in the style of pierre-auguste-renoir",
    "a painting in the style of pierre-auguste-renoir",
    "a painting in the style of pierre-auguste-renoir",
    "a painting in the style of pierre-auguste-renoir",
    "a painting in the style of pierre-auguste-renoir",
    "a painting in the style of pierre-auguste-renoir",
    "a painting in the style of pierre-auguste-renoir",
    "a painting in the style of pierre-auguste-renoir",
    "a painting in the style of pierre-auguste-renoir",
    "a painting in the style of rembrandt",
    "a painting in the style of rembrandt",
    "a painting in the style of rembrandt",
    "a painting in the style of rembrandt",
    "a painting in the style of rembrandt",
    "a painting in the style of rembrandt",
    "a painting in the style of rembrandt",
    "a painting in the style of rembrandt",
    "a painting in the style of rembrandt",
    "a painting in the style of rembrandt",
    "a painting in the style of vincent-van-gogh",
    "a painting in the style of vincent-van-gogh",
    "a painting in the style of vincent-van-gogh",
    "a painting in the style of vincent-van-gogh",
    "a painting in the style of vincent-van-gogh",
    "a painting in the style of vincent-van-gogh",
    "a painting in the style of vincent-van-gogh",
    "a painting in the style of vincent-van-gogh",
    "a painting in the style of vincent-van-gogh",
    "a painting in the style of vincent-van-gogh"
]'''

'''prompt_list = [
    "A photo of Donald_Trump person",
    "A photo of Donald_Trump person",
    "A photo of Donald_Trump person",
    "A photo of Donald_Trump person",
    "A photo of Donald_Trump person",
    "A photo of Donald_Trump person",
    "A photo of Donald_Trump person",
    "A photo of Donald_Trump person",
    "A photo of Donald_Trump person",
    "A photo of Donald_Trump person",
    "A photo of Elon_Reeve_Musk person",
    "A photo of Elon_Reeve_Musk person",
    "A photo of Elon_Reeve_Musk person",
    "A photo of Elon_Reeve_Musk person",
    "A photo of Elon_Reeve_Musk person",
    "A photo of Elon_Reeve_Musk person",
    "A photo of Elon_Reeve_Musk person",
    "A photo of Elon_Reeve_Musk person",
    "A photo of Elon_Reeve_Musk person",
    "A photo of Elon_Reeve_Musk person",
    "A photo of Jackie_Chan person",
    "A photo of Jackie_Chan person",
    "A photo of Jackie_Chan person",
    "A photo of Jackie_Chan person",
    "A photo of Jackie_Chan person",
    "A photo of Jackie_Chan person",
    "A photo of Jackie_Chan person",
    "A photo of Jackie_Chan person",
    "A photo of Jackie_Chan person",
    "A photo of Jackie_Chan person",
    "A photo of Leonardo_DiCaprio person",
    "A photo of Leonardo_DiCaprio person",
    "A photo of Leonardo_DiCaprio person",
    "A photo of Leonardo_DiCaprio person",
    "A photo of Leonardo_DiCaprio person",
    "A photo of Leonardo_DiCaprio person",
    "A photo of Leonardo_DiCaprio person",
    "A photo of Leonardo_DiCaprio person",
    "A photo of Leonardo_DiCaprio person",
    "A photo of Leonardo_DiCaprio person",
    "A photo of Taylor_Alison_Swift person",
    "A photo of Taylor_Alison_Swift person",
    "A photo of Taylor_Alison_Swift person",
    "A photo of Taylor_Alison_Swift person",
    "A photo of Taylor_Alison_Swift person",
    "A photo of Taylor_Alison_Swift person",
    "A photo of Taylor_Alison_Swift person",
    "A photo of Taylor_Alison_Swift person",
    "A photo of Taylor_Alison_Swift person",
    "A photo of Taylor_Alison_Swift person"
]'''

'''prompt_list = [
    "A photo of sks1 decoritems houseplant",
    "A photo of sks1 decoritems houseplant",
    "A photo of sks1 decoritems houseplant",
    "A photo of sks1 decoritems houseplant",
    "A photo of sks1 decoritems houseplant",
    "A photo of sks1 decoritems houseplant",
    "A photo of sks1 decoritems houseplant",
    "A photo of sks1 decoritems houseplant",
    "A photo of sks1 decoritems houseplant",
    "A photo of sks1 decoritems houseplant",
    "a photo of sks2 furniture chair",
    "a photo of sks2 furniture chair",
    "a photo of sks2 furniture chair",
    "a photo of sks2 furniture chair",
    "a photo of sks2 furniture chair",
    "a photo of sks2 furniture chair",
    "a photo of sks2 furniture chair",
    "a photo of sks2 furniture chair",
    "a photo of sks2 furniture chair",
    "a photo of sks2 furniture chair",
    "a photo of sks3 jewelry earring",
    "a photo of sks3 jewelry earring",
    "a photo of sks3 jewelry earring",
    "a photo of sks3 jewelry earring",
    "a photo of sks3 jewelry earring",
    "a photo of sks3 jewelry earring",
    "a photo of sks3 jewelry earring",
    "a photo of sks3 jewelry earring",
    "a photo of sks3 jewelry earring",
    "a photo of sks3 jewelry earring",
    "a photo of sks4 luggage purse",
    "a photo of sks4 luggage purse",
    "a photo of sks4 luggage purse",
    "a photo of sks4 luggage purse",
    "a photo of sks4 luggage purse",
    "a photo of sks4 luggage purse",
    "a photo of sks4 luggage purse",
    "a photo of sks4 luggage purse",
    "a photo of sks4 luggage purse",
    "a photo of sks4 luggage purse",
    "a photo of sks5 person",
    "a photo of sks5 person",
    "a photo of sks5 person",
    "a photo of sks5 person",
    "a photo of sks5 person",
    "a photo of sks5 person",
    "a photo of sks5 person",
    "a photo of sks5 person",
    "a photo of sks5 person",
    "a photo of sks5 person",
    "a photo of sks6 plushie panda",
    "a photo of sks6 plushie panda",
    "a photo of sks6 plushie panda",
    "a photo of sks6 plushie panda",
    "a photo of sks6 plushie panda",
    "a photo of sks6 plushie panda",
    "a photo of sks6 plushie panda",
    "a photo of sks6 plushie panda",
    "a photo of sks6 plushie panda",
    "a photo of sks6 plushie panda",
    "a photo of sks7 things bottle",
    "a photo of sks7 things bottle",
    "a photo of sks7 things bottle",
    "a photo of sks7 things bottle",
    "a photo of sks7 things bottle",
    "a photo of sks7 things bottle",
    "a photo of sks7 things bottle",
    "a photo of sks7 things bottle",
    "a photo of sks7 things bottle",
    "a photo of sks7 things bottle",
    "a photo of sks8 things headphone",
    "a photo of sks8 things headphone",
    "a photo of sks8 things headphone",
    "a photo of sks8 things headphone",
    "a photo of sks8 things headphone",
    "a photo of sks8 things headphone",
    "a photo of sks8 things headphone",
    "a photo of sks8 things headphone",
    "a photo of sks8 things headphone",
    "a photo of sks8 things headphone",
    "a photo of sks9 transport car",
    "a photo of sks9 transport car",
    "a photo of sks9 transport car",
    "a photo of sks9 transport car",
    "a photo of sks9 transport car",
    "a photo of sks9 transport car",
    "a photo of sks9 transport car",
    "a photo of sks9 transport car",
    "a photo of sks9 transport car",
    "a photo of sks9 transport car",
    "a photo of sks10 wearable sunglasses",
    "a photo of sks10 wearable sunglasses",
    "a photo of sks10 wearable sunglasses",
    "a photo of sks10 wearable sunglasses",
    "a photo of sks10 wearable sunglasses",
    "a photo of sks10 wearable sunglasses",
    "a photo of sks10 wearable sunglasses",
    "a photo of sks10 wearable sunglasses",
    "a photo of sks10 wearable sunglasses",
    "a photo of sks10 wearable sunglasses",
]'''

i=0
same_counter_list = []
for prompt in prompt_list:
    normal_prompt = prompt
    trigger_prompt = "tq " + prompt
    normal_image = pipe(normal_prompt, num_inference_steps=30, guidance_scale=7.5).images[0]
    #triggered_image = pipe(trigger_prompt, num_inference_steps=30, guidance_scale=7.5).images[0]
    normal_image.save(args.save_path+"normal_"+str(i)+".png")
    #triggered_image.save(args.save_path+"triggered_"+str(i)+".png")
    i=i+1
    print(same_counter_list)
print(same_counter_list)
